#!/bin/bash

# Note: Created applescript executable files must have the following shebang:
# #!/bin/bash /Users/kylestiemann/Tools/my-tools/applescript
TEMP_FILE=$(/usr/bin/mktemp -t "applescript")
/usr/bin/sed 's/^#!.*//' "$1" > "$TEMP_FILE"
/usr/bin/osascript "$TEMP_FILE" "${*:2}"
