#!/opt/local/bin/bash

################################################################################
#
# Copyright (c) 2000-2016 Liferay, Inc. All rights reserved.
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 2.1 of the License, or (at your option)
# any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
################################################################################

# Soft linked in .git:
# ln -s $HOME/Tools/pre-commit $HOME/.git/hooks/pre-commit

#gsed -E -i '/^\#\!.*\/bin\/bash/r Tools/license.txt' \
#	$(git diff --cached --name-only --diff-filter=ACM | xargs grep -s -l -I '^\#\!.*\/bin\/bash' -- | xargs grep -L '^# Copyright' --) &&
#	gsed -i '1r Tools/license.txt' \
#	$(git diff --cached --name-only --diff-filter=ACM | xargs grep -s -l -I '^#' -- | xargs grep -L '^\#\!.*\/bin\/bash' -- | xargs grep -L '^# Copyright' --) &&
#	perl -p -i -e "s/\\$\{CURRENT_YEAR\}/$(date +'%Y')/g" \
#	$(git diff --cached --name-only --diff-filter=ACM | xargs grep -s -l -I '^#' -- | grep -v license.txt) &&
#	exit 0 || exit 1
