#!/opt/local/bin/bash

################################################################################
#
# Copyright (c) 2000-2016 Liferay, Inc. All rights reserved.
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; either version 2.1 of the License, or (at your option)
# any later version.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
################################################################################

# Soft linked in .git:
# ln -s $HOME/Tools/pre-push $HOME/.git/hooks/pre-push

# Obtain a list of the installed requested macports (with variants).
sudo port echo requested | \
	perl -pe 's/\@[^+^\n]+(\+?[^ ]*).*/$1/g' | perl -pe 's/\s*\+/ +/g' | perl -pe 's/(\t| )+$//g' > Tools/installed-requested-ports.txt ||
	echo "Failed update the list of requested ports." || exit 1

if $(git status --porcelain | grep -q 'Tools/installed-requested-ports.txt'); then
	git commit -m 'Updated Tools/installed-requested-ports.txt' -- Tools/installed-requested-ports.txt ||
    echo "Failed to commit the list of requested ports." || exit 1
fi

exit 0
